name: docker


on:

  push:

  pull_request:


jobs:

  build_publish_containers:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    steps:

      - name: checkout repo

        uses: actions/checkout@v2
        
        with:
        
          submodules: recursive


      - name: build/push

        uses: whoan/docker-build-with-cache-action@v5

        with:

          registry: ghcr.io

          image_name: ${{ github.actor }}/test

          username: ${{ github.actor }}

          password: ${{ secrets.GITHUB_TOKEN }}
